
<?php
// Random PHP code generated by a language model

$myArray = array("apple", "banana", "cherry");

function getRandomItem($array) {
    $randomKey = array_rand($array);
    return $array[$randomKey];
}

echo getRandomItem($myArray);
?>